#ifndef Edition
#define Edition "full"
#endif
#define MyDataDirMarkerPrefix ".lingyaoime-data"
#if Edition == "full"
#define MyEditionIsFull 1
#define MyEditionAppName "Lingyao IME 灵耀输入法"
#define MyEditionAppId "{{A7C3E91F-4B2D-4E8A-9F1C-6D5E8B0A2C4D}"
#define MyEditionClsid "{E3062E9A-D834-4637-8958-ED8CFA427D01}"
#define MyEditionInstallDir "lingyaoime"
#define MyEditionRegistryKey "Software\Lingyao\LingyaoIME"
#define MyEditionWatchdogTask "Lingyao IME Watchdog"
#define MyEditionInstallerBaseName "LingyaoIME_Setup"
#define MyEditionDataDirMarker ".lingyaoime-data"
#define MyOtherEditionRegistryKeys "Software\Lingyao\LingyaoIME-Pinyin|Software\Lingyao\LingyaoIME-Wubi|Software\Lingyao\LingyaoIME-Japanese|Software\Lingyao\LingyaoIME-Vietnamese|Software\Lingyao\LingyaoIME-Tibetan"
#define MyOtherEditionInstallDirs "lingyaoime-pinyin|lingyaoime-wubi|lingyaoime-japanese|lingyaoime-vietnamese|lingyaoime-tibetan"
#elif Edition == "pinyin"
#define MyEditionIsFull 0
#define MyEditionAppName "Lingyao IME 灵耀拼音"
#define MyEditionAppId "{{EB4125FA-5687-4698-9E43-2C4CA4652132}"
#define MyEditionClsid "{7C927972-6D06-44C7-9B7C-B0D00C77D7C7}"
#define MyEditionInstallDir "lingyaoime-pinyin"
#define MyEditionRegistryKey "Software\Lingyao\LingyaoIME-Pinyin"
#define MyEditionWatchdogTask "Lingyao IME Watchdog (Pinyin)"
#define MyEditionInstallerBaseName "LingyaoIME-Pinyin_Setup"
#define MyEditionDataDirMarker ".lingyaoime-data.pinyin"
#define MyOtherEditionRegistryKeys "Software\Lingyao\LingyaoIME|Software\Lingyao\LingyaoIME-Wubi|Software\Lingyao\LingyaoIME-Japanese|Software\Lingyao\LingyaoIME-Vietnamese|Software\Lingyao\LingyaoIME-Tibetan"
#define MyOtherEditionInstallDirs "lingyaoime|lingyaoime-wubi|lingyaoime-japanese|lingyaoime-vietnamese|lingyaoime-tibetan"
#elif Edition == "wubi"
#define MyEditionIsFull 0
#define MyEditionAppName "Lingyao IME 灵耀五笔"
#define MyEditionAppId "{{FF5943BF-0F4B-4999-8504-15235E4516C6}"
#define MyEditionClsid "{FD41CA20-BA49-41FE-96BE-923DCCA191DA}"
#define MyEditionInstallDir "lingyaoime-wubi"
#define MyEditionRegistryKey "Software\Lingyao\LingyaoIME-Wubi"
#define MyEditionWatchdogTask "Lingyao IME Watchdog (Wubi)"
#define MyEditionInstallerBaseName "LingyaoIME-Wubi_Setup"
#define MyEditionDataDirMarker ".lingyaoime-data.wubi"
#define MyOtherEditionRegistryKeys "Software\Lingyao\LingyaoIME|Software\Lingyao\LingyaoIME-Pinyin|Software\Lingyao\LingyaoIME-Japanese|Software\Lingyao\LingyaoIME-Vietnamese|Software\Lingyao\LingyaoIME-Tibetan"
#define MyOtherEditionInstallDirs "lingyaoime|lingyaoime-pinyin|lingyaoime-japanese|lingyaoime-vietnamese|lingyaoime-tibetan"
#elif Edition == "japanese"
#define MyEditionIsFull 0
#define MyEditionAppName "Lingyao IME 灵耀日语"
#define MyEditionAppId "{{41454B5E-8298-42B8-BA6F-5DD2FE559E5E}"
#define MyEditionClsid "{43218C33-7729-47CC-A485-5F43B77F696A}"
#define MyEditionInstallDir "lingyaoime-japanese"
#define MyEditionRegistryKey "Software\Lingyao\LingyaoIME-Japanese"
#define MyEditionWatchdogTask "Lingyao IME Watchdog (Japanese)"
#define MyEditionInstallerBaseName "LingyaoIME-Japanese_Setup"
#define MyEditionDataDirMarker ".lingyaoime-data.japanese"
#define MyOtherEditionRegistryKeys "Software\Lingyao\LingyaoIME|Software\Lingyao\LingyaoIME-Pinyin|Software\Lingyao\LingyaoIME-Wubi|Software\Lingyao\LingyaoIME-Vietnamese|Software\Lingyao\LingyaoIME-Tibetan"
#define MyOtherEditionInstallDirs "lingyaoime|lingyaoime-pinyin|lingyaoime-wubi|lingyaoime-vietnamese|lingyaoime-tibetan"
#elif Edition == "vietnamese"
#define MyEditionIsFull 0
#define MyEditionAppName "Lingyao IME 灵耀越南语"
#define MyEditionAppId "{{BA5F9864-3095-469D-BCB5-B0562EB51263}"
#define MyEditionClsid "{0CFED878-B045-4604-8DED-845A7C80CABE}"
#define MyEditionInstallDir "lingyaoime-vietnamese"
#define MyEditionRegistryKey "Software\Lingyao\LingyaoIME-Vietnamese"
#define MyEditionWatchdogTask "Lingyao IME Watchdog (Vietnamese)"
#define MyEditionInstallerBaseName "LingyaoIME-Vietnamese_Setup"
#define MyEditionDataDirMarker ".lingyaoime-data.vietnamese"
#define MyOtherEditionRegistryKeys "Software\Lingyao\LingyaoIME|Software\Lingyao\LingyaoIME-Pinyin|Software\Lingyao\LingyaoIME-Wubi|Software\Lingyao\LingyaoIME-Japanese|Software\Lingyao\LingyaoIME-Tibetan"
#define MyOtherEditionInstallDirs "lingyaoime|lingyaoime-pinyin|lingyaoime-wubi|lingyaoime-japanese|lingyaoime-tibetan"
#elif Edition == "tibetan"
#define MyEditionIsFull 0
#define MyEditionAppName "Lingyao IME 灵耀藏文"
#define MyEditionAppId "{{68802231-3EDF-4B67-B80F-DFB95A1BAD01}"
#define MyEditionClsid "{93DEEE80-9145-4257-BF11-957FDFE0A75E}"
#define MyEditionInstallDir "lingyaoime-tibetan"
#define MyEditionRegistryKey "Software\Lingyao\LingyaoIME-Tibetan"
#define MyEditionWatchdogTask "Lingyao IME Watchdog (Tibetan)"
#define MyEditionInstallerBaseName "LingyaoIME-Tibetan_Setup"
#define MyEditionDataDirMarker ".lingyaoime-data.tibetan"
#define MyOtherEditionRegistryKeys "Software\Lingyao\LingyaoIME|Software\Lingyao\LingyaoIME-Pinyin|Software\Lingyao\LingyaoIME-Wubi|Software\Lingyao\LingyaoIME-Japanese|Software\Lingyao\LingyaoIME-Vietnamese"
#define MyOtherEditionInstallDirs "lingyaoime|lingyaoime-pinyin|lingyaoime-wubi|lingyaoime-japanese|lingyaoime-vietnamese"
#else
#error Unknown edition; use /DEdition= one of full, pinyin, wubi, japanese, vietnamese, tibetan
#endif
