# 本次构建的产品版本（shared/contracts/editions.json 的 id）。shared/contracts/lingyao_edition.h 按这里定义的 LINGYAO_EDITION_<ID> 选出该版本的 CLSID、管道名、注册表键和目录名；TSF DLL、Server、看门狗和 prepare 工具在编译期就绑定到一个版本，所以每个版本各编一次。缺省是 full，与引入版本之前的构建完全相同。
include_guard(GLOBAL)
set(LINGYAO_EDITION "full" CACHE STRING "Product edition to build (an id in shared/contracts/editions.json with a Windows section)")
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../shared/contracts/editions.json" lingyao_editions_json)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_LIST_DIR}/../../shared/contracts/editions.json")
string(JSON lingyao_edition_count LENGTH "${lingyao_editions_json}" editions)
set(lingyao_edition_known OFF)
set(lingyao_edition_ids "")
math(EXPR lingyao_edition_last "${lingyao_edition_count} - 1")
foreach(lingyao_edition_index RANGE ${lingyao_edition_last})
  string(JSON lingyao_edition_id GET "${lingyao_editions_json}" editions ${lingyao_edition_index} id)
  string(JSON lingyao_edition_windows TYPE "${lingyao_editions_json}" editions ${lingyao_edition_index} platforms windows)
  if(lingyao_edition_windows STREQUAL "OBJECT")
    list(APPEND lingyao_edition_ids "${lingyao_edition_id}")
    if(lingyao_edition_id STREQUAL LINGYAO_EDITION)
      set(lingyao_edition_known ON)
    endif()
  endif()
endforeach()
if(NOT lingyao_edition_known)
  message(FATAL_ERROR "LINGYAO_EDITION=${LINGYAO_EDITION} is not an edition with Windows identifiers; choose one of: ${lingyao_edition_ids}")
endif()
string(TOUPPER "${LINGYAO_EDITION}" lingyao_edition_macro)
add_compile_definitions(LINGYAO_EDITION_${lingyao_edition_macro})
