# 本次构建的产品版本（shared/contracts/editions.json 的 id）。platforms/linux/src/core/LinuxEdition.h 按这里定义的 LINGYAO_EDITION_<ID> 选出该版本的每用户目录、IBus 引擎名、Fcitx5 插件名和命令名，所以每个版本各编一次。缺省是 full，与引入版本之前的构建完全相同：同样的前缀、同样的文件和名字，脚本与数据文件原样安装。
#
# 其他版本是独立的包，装在自己的前缀（版本表的 install_prefix，/opt/lingyao-linux-<id>）下。CMAKE_INSTALL_PREFIX 等于这个前缀时（打包就是这样），系统按名字查找的那几样（IBus 组件、Fcitx5 插件与条目、systemd 用户单元、桌面入口、XDG 自启动项、图标和 /usr/bin 下的两个命令）装到系统目录；开发时换成别的前缀则全部留在前缀里，不碰系统目录。脚本和数据文件在配置阶段由 platforms/linux/scripts/edition_linux.py 按版本改写一份再安装。
include_guard(GLOBAL)
set(LINGYAO_EDITION "full" CACHE STRING "Product edition to build (an id in shared/contracts/editions.json with a Linux section)")
set(LINGYAO_EDITIONS_JSON "${CMAKE_CURRENT_LIST_DIR}/../../../shared/contracts/editions.json")
file(READ "${LINGYAO_EDITIONS_JSON}" lingyao_editions_json)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${LINGYAO_EDITIONS_JSON}")
string(JSON lingyao_edition_count LENGTH "${lingyao_editions_json}" editions)
set(lingyao_edition_index_found "")
set(lingyao_edition_ids "")
math(EXPR lingyao_edition_last "${lingyao_edition_count} - 1")
foreach(lingyao_edition_index RANGE ${lingyao_edition_last})
  string(JSON lingyao_edition_id GET "${lingyao_editions_json}" editions ${lingyao_edition_index} id)
  string(JSON lingyao_edition_linux TYPE "${lingyao_editions_json}" editions ${lingyao_edition_index} platforms linux)
  if(lingyao_edition_linux STREQUAL "OBJECT")
    list(APPEND lingyao_edition_ids "${lingyao_edition_id}")
    if(lingyao_edition_id STREQUAL LINGYAO_EDITION)
      set(lingyao_edition_index_found "${lingyao_edition_index}")
    endif()
  endif()
endforeach()
if(lingyao_edition_index_found STREQUAL "")
  message(FATAL_ERROR "LINGYAO_EDITION=${LINGYAO_EDITION} is not an edition with Linux identifiers; choose one of: ${lingyao_edition_ids}")
endif()
string(TOUPPER "${LINGYAO_EDITION}" lingyao_edition_macro)
add_compile_definitions(LINGYAO_EDITION_${lingyao_edition_macro})

# 版本表 platforms.linux 的字段。
foreach(lingyao_edition_field package install_prefix client_directory ibus_engine fcitx5_addon tauri_identifier)
  string(TOUPPER "${lingyao_edition_field}" lingyao_edition_variable)
  string(JSON LINGYAO_EDITION_${lingyao_edition_variable} GET "${lingyao_editions_json}"
         editions ${lingyao_edition_index_found} platforms linux ${lingyao_edition_field})
endforeach()
string(JSON LINGYAO_EDITION_DISPLAY_NAME GET "${lingyao_editions_json}" editions ${lingyao_edition_index_found} display_name zh-Hans)
string(JSON LINGYAO_EDITION_DISPLAY_NAME_EN GET "${lingyao_editions_json}" editions ${lingyao_edition_index_found} display_name en)
string(JSON lingyao_edition_language_dictionaries LENGTH "${lingyao_editions_json}"
       editions ${lingyao_edition_index_found} language_dictionaries)
# 每用户目录名，也是前缀下 share、lib、doc 和 /etc 里的子目录名；full 是 lingyao-client。
set(LINGYAO_CLIENT_DIRECTORY "${LINGYAO_EDITION_CLIENT_DIRECTORY}")
# 装进前缀的 Host API 库的名字（lib<stem>.so）。Cargo 产出的库没有 SONAME，CMake 于是用 -l<stem> 链接，插件和程序的 DT_NEEDED 就是这个文件名。同一个 fcitx5 进程按 DT_NEEDED 的名字认已经加载过的库，两个版本同名时后加载的插件会用上先加载的那个版本的库，所以除 full 以外的版本都换一个名字。
if(LINGYAO_EDITION STREQUAL "full")
  set(LINGYAO_HOST_LIBRARY_STEM "lingyao_host_api")
else()
  set(LINGYAO_HOST_LIBRARY_STEM "lingyao_host_api_${LINGYAO_EDITION}")
endif()
if(LINGYAO_EDITION STREQUAL "full")
  set(LINGYAO_EDITION_IS_FULL ON)
  set(LINGYAO_EDITION_RESOURCE_LOCK "${CMAKE_CURRENT_LIST_DIR}/../../../resources/desktop-dictionary.lock.json")
else()
  set(LINGYAO_EDITION_IS_FULL OFF)
  set(LINGYAO_EDITION_RESOURCE_LOCK "${CMAKE_CURRENT_LIST_DIR}/../../../resources/editions/${LINGYAO_EDITION}.lock.json")
endif()
# 本版本是否带中文主词库（版本表 resources.components 有 chinese-main）。落定重排模型（整句模型）只给中文整句重排，不带中文主词库的版本（日文、越南文、藏文版）不装它。
string(JSON lingyao_edition_component_count LENGTH "${lingyao_editions_json}" editions ${lingyao_edition_index_found} resources components)
set(LINGYAO_EDITION_CHINESE_MAIN OFF)
if(lingyao_edition_component_count GREATER 0)
  math(EXPR lingyao_edition_component_last "${lingyao_edition_component_count} - 1")
  foreach(lingyao_edition_component_index RANGE ${lingyao_edition_component_last})
    string(JSON lingyao_edition_component GET "${lingyao_editions_json}"
           editions ${lingyao_edition_index_found} resources components ${lingyao_edition_component_index})
    if(lingyao_edition_component STREQUAL "chinese-main")
      set(LINGYAO_EDITION_CHINESE_MAIN ON)
    endif()
  endforeach()
endif()
# 本版本是否提供手写、是否带非英文离线释义（版本表 features.handwriting、features.offline_glosses）。手写模型只认汉字，离线释义按中文候选查，两者都只给提供中文方案的版本；日文、越南文和藏文版不装手写模型和离线释义数据库。
foreach(lingyao_edition_feature handwriting offline_glosses)
  string(TOUPPER "${lingyao_edition_feature}" lingyao_edition_feature_variable)
  string(JSON lingyao_edition_feature_value GET "${lingyao_editions_json}"
         editions ${lingyao_edition_index_found} features ${lingyao_edition_feature})
  if(lingyao_edition_feature_value)
    set(LINGYAO_EDITION_${lingyao_edition_feature_variable} ON)
  else()
    set(LINGYAO_EDITION_${lingyao_edition_feature_variable} OFF)
  endif()
endforeach()
# 本版本是否用到粤语、注音和笔画词库；不用的版本不装它们。
if(lingyao_edition_language_dictionaries GREATER 0)
  set(LINGYAO_EDITION_LANGUAGE_DICTIONARIES ON)
else()
  set(LINGYAO_EDITION_LANGUAGE_DICTIONARIES OFF)
endif()
# 是否把系统按名字查找的文件装到系统目录：只有不是 full、而且前缀就是版本自己的前缀时。full 的这些文件今天就在 /usr 前缀下的相对位置，不变。
if(NOT LINGYAO_EDITION_IS_FULL AND CMAKE_INSTALL_PREFIX STREQUAL LINGYAO_EDITION_INSTALL_PREFIX)
  set(LINGYAO_EDITION_SYSTEM_PATHS ON)
  set(LINGYAO_SYSTEM_DATADIR "/usr/share")
  set(LINGYAO_SYSTEM_FULL_DATADIR "/usr/share")
else()
  set(LINGYAO_EDITION_SYSTEM_PATHS OFF)
  set(LINGYAO_SYSTEM_DATADIR "${CMAKE_INSTALL_DATADIR}")
  set(LINGYAO_SYSTEM_FULL_DATADIR "${CMAKE_INSTALL_FULL_DATADIR}")
endif()
if(NOT LINGYAO_EDITION_IS_FULL)
  find_package(Python3 COMPONENTS Interpreter REQUIRED)
endif()

# 本版本要安装的那份脚本或数据文件，路径写进 <variable>。full 就是仓库里的文件；其他版本是 edition_linux.py 改写的副本，规则没有全部命中或留下 full 的名字时配置失败。
function(lingyao_edition_source variable relative)
  set(source "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../${relative}")
  if(LINGYAO_EDITION_IS_FULL)
    set(${variable} "${source}" PARENT_SCOPE)
    return()
  endif()
  set(output "${CMAKE_BINARY_DIR}/edition/${relative}")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../scripts/edition_linux.py")
  execute_process(
    COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../scripts/edition_linux.py"
            render --edition "${LINGYAO_EDITION}" --input "${source}" --output "${output}"
    RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot render ${relative} for edition ${LINGYAO_EDITION}")
  endif()
  set(${variable} "${output}" PARENT_SCOPE)
endfunction()

# 把 <variable> 指向的 Cargo 产出的 Host API 库换成本版本的文件名：full 原样不动，其他版本在配置阶段复制一份 lib<stem>.so 到构建目录，之后的链接与安装都用这份。库重新编译后，configure_file 让下一次构建先重新配置、再复制一遍。
function(lingyao_edition_host_library variable)
  set(output "${CMAKE_BINARY_DIR}/edition/host/lib${LINGYAO_HOST_LIBRARY_STEM}.so")
  if(LINGYAO_EDITION_IS_FULL OR "${${variable}}" STREQUAL output)
    return()
  endif()
  configure_file("${${variable}}" "${output}" COPYONLY)
  set(${variable} "${output}" PARENT_SCOPE)
endfunction()
